#!/bin/bash

SCRIPT_FILE=$WERCKER_METRONOME_ONE_OFF_JOB_SCRIPT_FILE
JSON_FILE=$WERCKER_METRONOME_ONE_OFF_JOB_JSON_FILE
DCOS_URL=$WERCKER_METRONOME_ONE_OFF_JOB_DCOS_URL
TIME_LIMIT=$WERCKER_METRONOME_ONE_OFF_JOB_TIME_LIMIT

python "$WERCKER_STEP_ROOT/script.py" "$JSON_FILE" "$DCOS_URL" "$TIME_LIMIT"

if [ $? -eq 0 ]
then
    success "\nJob success"
else
    error "\nJob error"
fi
